### ISSUE TITLE
Enviar tweet avisando que foi verificado que o site voltou.

### ISSUE THREAD

**Issue by anapaulamendes** [colaboradados/colabora_bot#18]
> Como os portais de transparência podem ser instáveis sugiro duas coisas para evitar que o bot passe a impressão de que está acusando erroneamente:
> 
> 1. Aumentar o período entre as 10 tentativas de entrar no site, ou a quantidade de tentativas, e
> 2. Enviar tweet avisando que foi verificado que o site voltou.
> 
> Talvez esse segundo seja interessante verificar de 5 em 5 minutos ou algo do tipo. Dependendo no futuro pode-se começar a coletar esses dados e criar um ranking de portais mais instáveis, ou algo mais interessante.

A nº 1 já está implementada.
Implementar a nº 2.
Sugestão do @gusrabbit  :smile:

**Comment by luchiago** [comment]
Olá, gostaria de trabalhar nessa issue.

**Comment by anapaulamendes** [comment]
Assinada para você @luchiago :smile:

**Comment by exageraldo** [comment]
@luchiago Estava pensando em outra forma de implementação.

Usando um dicionario, por exemplo, para colocar as URLs que falharam, e na próxima vez que for verificado e der tudo certo, ele manda um tweet avisando.

Dependendo de como seja estruturado, pode usar o Redis. Por exemplo, se quiser colocar um tempo X para tentar novamente, cria uma estrutura chave-valor no redis, com um tempo de expiração, quando o valor não estiver mais lá, tenta-se novamente capturar os dados daquela url.

**Comment by rcapp** [comment]
Bom dia! 

Esse problema ainda está aberto? Caso o pedidod de `pull` #25  não o resolva, o que ainda está errado ou falta ser implementado?

Obrigado!
