### ISSUE TITLE
Criar integração contínua

### ISSUE THREAD

**Issue by anapaulamendes** [colaboradados/colabora_bot#27]
Com um maior número de contribuições e aumento da complexidade do bot, é necessário criar integração contínua para evitar problemas.

**Comment by jeduardo824** [comment]
Podemos utilizar o GitHub Actions, o que acha? Acho que posso ajudar 😄 @anapaulamendes

**Comment by jeduardo824** [comment]
Podemos fazer as configurações iniciais com alguns testes e em seguida criar novas issues para a criação de testes...

**Comment by anapaulamendes** [comment]
Oi @jeduardo824 vou subir a nova atualização do bot e atualizar as issues. Essa vai continuar, se quiser trabalhar nela.
