### ISSUE TITLE
Atualizar o README-en.md (versão em inglês do README.md)

### ISSUE THREAD

**Issue by anapaulamendes** [colaboradados/colabora_bot#28]
A versão do README.md em português foi atualizada, mas em inglês ainda não.

**Comment by sosolidkk** [comment]
Olá, eu poderia pegar essa issue? Caso não tenha sido feita ainda.

**Comment by anapaulamendes** [comment]
Oi, @sosolidkk , pode sim! A versão em português foi atualizada, mas em inglês ainda não.
