### ISSUE TITLE
Colaborações

### ISSUE THREAD

**Issue by LucianaMarques** [colaboradados/colabora_bot#3]
Oi pessoal!

Achei muito massa o projeto, mas de fato a criação da conta developer no twitter acaba sendo um impeditivo (eu apliquei pro processo mas nunca recebi nenhum retorno). 

Não seria legal migrar o projeto para outras plataformas? 

Estou disposta a contribuir :)

**Comment by LucianaMarques** [comment]
Eu não vi toda a base de código, mas algo que tem se tornado popular são os bots de Telegram! Teria que estudar a viabilidade, mas o que vocês acham?

**Comment by brilvio** [comment]
Bots para telegram são fáceis de fazer, mas não ficaria visível para pessoas que não tenham adicionado/conversado com o bot. 

Não posso falar pela galera que fez o projeto mas acho que o intuito é:

1. Anunciar publicamente que o site está fora do ar.
2. Avisar a órgão governamental que o site está fora do ar.

Me corrigem se eu estiver errado.

**Comment by gilsondev** [comment]
Como o @brilvio com o Telegram é tranquilo de montar, o problema seria o alcance. Até o momento o Twitter é melhor para isso. Estou pensando em outras plataforma que não seja o Facebook por exemplo, mas não vem nada. Sugestões?

**Comment by juditecypreste** [comment]
O Twitter é a forma mais automatizada que temos e com maior alcance. Estamos pensando em produzir balanços semanais/mensais sobre o que vem acontecendo. 
Acredito que o Telegram é uma boa saída, mas realmente o alcance pode ser menor. Talvez um grupo onde as pessoas se incluam (ex: PyJobs) e mande mensagens de forma automática seja a melhor escolha.

**Comment by jovemadulto** [comment]
Lembrei-me de uma plataforma parecida com o Twitter, mas que pode servir como um substituto no futuro: o [https://joinmastodon.org/](Mastodon).

O alcance é reduzido também, porém é simples de montar uma timeline similar a do Twitter e algumas instâncias são permissivas quanto a bots. O que acham?

**Comment by kelvinrferreira** [comment]
Twitter por ter o conceito de "Microblog" e ser totalmente publico e ter alto impacto acredito ser o melhor lugar mesmo pro bot viver. 

Agora sobre o problema principal da issue que a @LucianaMarques comentou (API do twitter demora ser aprovada) pode ser que seja fácil de resolver.

Se for aplicado o conceito de injeção de dependencia ou mesmo o de factory podemos fornecer uma instancia da twitter api com dados falsos que vao escrever os tweets em outro lugar pra analise (ex: console) CASO o environment for de desenvolvimento.

Tenho a intenção de contribuir para o projeto depois que voltar de uma viagem (semana que vem), então posso tomar frente disso e abrir um PR pra vcs.

Mas caso tiverem interesse, tem umas boas referencias aqui:
- https://medium.com/@shivama205/dependency-injection-python-cb2b5f336dce
- http://python-dependency-injector.ets-labs.org/introduction/di_in_python.html
