### ISSUE TITLE
Lidar com sites instáveis

### ISSUE THREAD

**Issue by gusrabbit** [colaboradados/colabora_bot#4]
Como os portais de transparência podem ser instáveis sugiro duas coisas para evitar que o bot passe a impressão de que está acusando erroneamente:

1. Aumentar o período entre as 10 tentativas de entrar no site, ou a quantidade de tentativas, e
2. Enviar tweet avisando que foi verificado que o site voltou.

Talvez esse segundo seja interessante verificar de 5 em 5 minutos ou algo do tipo. Dependendo no futuro pode-se começar a coletar esses dados e criar um ranking de portais mais instáveis, ou algo mais interessante.

**Comment by gilsondev** [comment]
Estava pensando nisso também. Será que um `sleep` seria o suficiente ou não? Além disso caso tenha esse delay, é bom preparar para que o bot possa fazer separadamente para cada site para não ficar enfileirado.

**Comment by gilsondev** [comment]
Testando o código aqui, que está com `timeout=10`, no caso do portal da transparência do Belém, ele não está fora do ar mas excede o tempo descrito. Nesse caso é bom pensar em aumentar o tempo para 30 pelo menos?

**Comment by gilsondev** [comment]
> Dependendo no futuro pode-se começar a coletar esses dados e criar um ranking de portais mais instáveis, ou algo mais interessante.

É uma boa idéia. Fazer logging dessas informações para fazer uma extração dos dados para fazer esse ranking. Isso pode ser uma issue separada.

**Comment by juditecypreste** [comment]
Nós vamos elaborar uma espécie de armazenamento para os tweets, e dessa forma ter um banco para análises posteriores. Com relação ao tempo excedido, pensamos que 10 era um bom tempo, mas sites governamentais são bem instáveis. Talvez 30 seja melhor...

**Comment by gilsondev** [comment]
Quanto tiver novidades nos avise, que no que precisar de contribuição, estou à disposição.

**Comment by jovemadulto** [comment]
Para o logging estou pensando em manter planilhas no Google Sheets que serão criadas a partir de um determinado tempo (diariamente, semanalmente...?) e esta alimentada pelo bot assim que encontrar algum erro nas páginas. Esses arquivos serão, então, transferidos para uma pasta pública no Google Drive ou de terceiros...
Acredito que assim facilitará a análise futura como o @gusrabbit propôs.

Quais informações vocês acham interessantes de coletar?

**Comment by gilsondev** [comment]
É uma boa @jovemadulto. Poderia fazer coletas diárias para termos uma linha do tempo, e assim podermos usar para análise dos dados.

A princípio os dados a coletar podem ser:

 - Portal a ser verificada
 - Resultado do "ping"
 - Momento em que foi feito a requisição
 - Momento em que recebeu a resposta da requisição
 - Nome da cidade

Está bom assim @gusrabbit ?

**Comment by gmonnerat** [comment]
Alguns sites são bloqueados para bots ou acesso do exterior.

Por exemplo:
```bash
curl http://transparencia.fortaleza.ce.gov.br

<div id="alert_text">Bloqueado pela politica de segurança<BR>Contato: cfs@sefin.fortaleza.ce.gov.br</div></div><p>Block reason: <b>Gateway GEO-IP Filter Alert</b>
```

```bash
(calabora) gabriel@localhost:~/colaboradados-o-bot$ curl -I http://transparencia.fortaleza.ce.gov.br
HTTP/1.0 403 Forbidden
Content-Type: text/html; charset=utf-8
Window-target: _top
Connection: close
```

Eu acessei de um servidor Linode.

Se eu fizer o mesmo do Brasil, requests.get em Python não falha.

**Comment by juditecypreste** [comment]
Oi @gmonnerat!
A mágica é exatamente essa! Temos que usar um servidor de fora mesmo, e mostrar que os sites não são acessíveis. 
Se você é um cidadão brasileiro que está fora do seu país e não consegue acessar dados de transparência governamental isso é, no mínimo errado. 
Ou seja, não somos nós que devemos mudar nosso código para que funcione como um ''pc brasileiro". Os órgão que devem mudar as configurações de seus sites.

**Comment by gmonnerat** [comment]
@gilsondev [Status Page](https://www.statuspage.io/features/uptime-and-performance) faz isso muito bem. Por exemplo, https://status.lineageos.org/.

E com as informações que você quer coletar, dá para gerar algo bem parecido.

**Comment by gmonnerat** [comment]
@juditecypreste Entendi! Faz todo sentido.

Li a thread rápido d+ e no código não achei um exception para Forbidden e entendi como não esperado.
