### ISSUE TITLE
Dúvidas sobre a Infraestrutura do bot

### ISSUE THREAD

**Issue by kelvinrferreira** [colaboradados/colabora_bot#9]
Oi, 

Analisando o repositório não pude encontrar nenhuma informação sobre onde esse bot está rodando/hospedado.

Poderiam dar mais detalhes e colocar uma seção no README.md? Isso vai ser importante pra entender as limitações do bot e as possiblidades.

tnks 👍

**Comment by gmonnerat** [comment]
up

**Comment by thiagoferreiraw** [comment]
Olá pessoal, também tenho interesse nesse tópico. @anapaulamendes pode nos ajudar?
